### ISSUE TITLE
oct 25 intro crypto meeting notes

### ISSUE THREAD

**Issue by ianklatzco** [sigpwny/meetings_old#1]
courtesy cryptocatz slack

[DHKE example (youtube)](https://www.youtube.com/watch?v=U62S8SchxX4) (i have lock boxes that we could use to recreate this, but idk what to actually lock them with)

https://github.com/justintroutman/pocketblock `PocketBlock is surprisingly fun for all ages, and teaches the rudiments of how AES actually works in a way you can do it with pencil and paper` so need to compile the latex to pdf

just do picoctf crypto: https://2018game.picoctf.com/problems

hsctf crypto: https://jacobedelman.gitbooks.io/hsctf-3-practice-problems/content/text2numbers-problem.html

**Comment by trevorm4** [comment]
https://www.garykessler.net/library/crypto.html

**Comment by ianklatzco** [comment]
@142393208578637824
